language: node_js
node_js:
  - "0.10"
env:
  global:
  - SAUCE_USERNAME: douglashipolito
  - secure: e+4y7ABujyG/ojYqTOv46oe20pLsPaZ5nuy36Lr53Q51kiELhIBe8VTDcZvYaL6IzC1tWOQ6c4drTpPDxYT8/10Jdn4+gtSTSMMBAwY+GTkUH/tYZZZCR8yDg2iQu5i3gRAdJWLQZiTheIu99XNbj9yMgvqg+X1c21jVSWZ+Fdg=
  - secure: Ra6z8HWzWYv/rW8hAfEEq144njY7vagP+6hjoGwgRz+xYkN3Kv4ZcHvM2RVOtXV7ofbZt/ZZU2jx1pUmS8gqk2rTnLq01A//P8mxrFDRDZk8MiIXkXAht1WfWUiyGIeHF3HvHiZ9ZqxXSVkouKdgb6t+479LdX0ydsnHMw7dOd4=
notifications:
  email: false
before_script: npm install -g karma-cli
